sonar.projectKey=time0mal_flask-app-github-actions-argocd
sonar.organization=time0mal


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=Flask-App-GitHub-Actions-ArgoCD
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
